### ISSUE TITLE
是否可以扩大成衡中模式的所有高中

### ISSUE THREAD

**Issue by Ode1l** [HZSB-Editorial/HZSB#10]
我所在的河南，有众多高中都在模仿衡中模式。据我了解河南的小地方还有更过分的行为，比如扣押学生高考成绩单，拿走学生投报志愿网站密码，强制报学校等等。

**Comment by ShuJun-Junical** [comment]
首先给予你肯定的回复。

由于团队成员精力和能力均有限，这些文章、证据还需广大同志们来补充。

如果你有好的想法或证据，可以整理成文章，向我们网站投稿（在此 issue 下回复你的文章、开 pr 自行添加你的文章均可），但文章内容需要符合我站[投稿规范](https://hzsb.info/contribute.html)。
